/**
 * Ingilizce arayuz sozlugu: Turkce kaynak metin → Ingilizce.
 * Kurallar ve neden anahtarin Turkce metin oldugu: bkz. src/dil.ts.
 * Eksik ya da fazla yer tutucu `dil.test.ts`te yakalaniyor.
 */
export const EN: Record<string, string> = {
  "Çıkmak istiyor musun?": "Do you want to quit?",
  "İlerlemen kayıtlı, kaldığın yerden devam edebilirsin.": "Your progress is saved — you can pick up where you left off.",
  "Vazgeç": "Cancel",
  "Çık": "Quit",
  "Halka": "Ring",
  "Halat": "Rope",
  "Bronz": "Bronze",
  "Gümüş": "Silver",
  "Altın": "Gold",
  "Elmas": "Diamond",
  "{esik} kelime": "{esik} words",
  "{esik} gün üst üste": "{esik} days in a row",
  "Seti bitir": "Finish the set",
  "İngilizcesi ne?": "What's the English?",
  "Ne duyuyorsun?": "What do you hear?",
  "Dokun, tekrar dinle": "Tap to listen again",
  "görsel gelecek": "image coming soon",
  "İngilizcesi hangisi?": "Which is the English?",
  "Türkçesi hangisi?": "Which is the Turkish?",
  "Çıkış": "Sign out",
  "Bağlanamadık": "We couldn't connect",
  "Son ilerlemen hesabına": "Your latest progress",
  "gönderilemedi": "couldn't be sent",
  ". Şimdi çıkarsan o kısım kaybolur. İnternetin gelince tekrar dene.": " to your account. If you sign out now, that part will be lost. Try again once you're online.",
  "Yine de çık": "Sign out anyway",
  "Çıkış yapılsın mı?": "Sign out?",
  "İlerlemen hesabında kalır, tekrar girince geri gelir.": "Your progress stays in your account and comes back when you sign in again.",
  "Çıkılıyor…": "Signing out…",
  "Çıkış yap": "Sign out",
  "Devam": "Continue",
  "Bir şeyler ters gitti.": "Something went wrong.",
  "Adresini doğrula": "Verify your email",
  "{eposta} adresine bir doğrulama bağlantısı yolladık. Aç, dokun, geri dön.": "We sent a verification link to {eposta}. Open it, tap the link, come back.",
  "Gelmediyse spam klasörüne bak. Birkaç dakika sürebiliyor.": "Didn't get it? Check your spam folder. It can take a few minutes.",
  "Sıfırlama bağlantısı yolda": "Reset link on its way",
  "{eposta} adresine şifre belirleme bağlantısı gönderdik.": "We sent a link to set your password to {eposta}.",
  "Gelmediyse spam klasörüne bak.": "Didn't get it? Check your spam folder.",
  "Google ile girilemedi.": "Couldn't sign in with Google.",
  "Tekrar hoş geldin": "Welcome back",
  "İlerlemen hesabında duruyor; kaldığın yerden devam edersin.": "Your progress is in your account — pick up right where you left off.",
  "Giriş yap": "Sign in",
  "İlerlemeni kaydet": "Save your progress",
  "Telefonunu değiştirsen de, tarayıcını temizlesen de kaldığın yerden devam edersin.": "Change phones or clear your browser — you'll still pick up where you left off.",
  "Hesap aç": "Create account",
  "Şifreni mi unuttun?": "Forgot your password?",
  "Adresini yaz, yeni şifre belirleme bağlantısı gönderelim.": "Enter your email and we'll send you a link to set a new password.",
  "Bağlantı gönder": "Send link",
  "Yeni şifreni belirle": "Set a new password",
  "Bundan sonra bu şifreyle gireceksin.": "You'll sign in with this password from now on.",
  "Şifreyi kaydet": "Save password",
  "Bilgilerin": "Your details",
  "Seviye ve hedef isteğe bağlı.": "Level and goal are optional.",
  "Kaydet": "Save",
  "Tamam": "OK",
  "Google ile devam et": "Continue with Google",
  "veya": "or",
  "Adın": "Your name",
  "İngilizcen ne durumda?": "How's your English?",
  "Niçin öğreniyorsun?": "Why are you learning?",
  "E-posta": "Email",
  "Şifre": "Password",
  "Şifreyi gizle": "Hide password",
  "Şifreyi göster": "Show password",
  "Gizle": "Hide",
  "Göster": "Show",
  "Gönderiliyor…": "Sending…",
  "Sonra doldururum": "I'll do it later",
  "Şimdi değil": "Not now",
  "Şifremi unuttum": "Forgot password",
  "Hesabın yok mu?": "No account yet?",
  "Hesabın var mı?": "Already have an account?",
  "Girişe dön": "Back to sign in",
  "Seviye ve hedefi sonra Ayarlar'dan da değiştirebilirsin.": "You can change your level and goal later in Settings.",
  "Kaydedilemedi.": "Couldn't save.",
  "Giriş yapıldı": "Signed in",
  "İlerlemen hesabına bağlandı. Hangi cihazdan girersen gir kaldığın yerden devam edersin.": "Your progress is linked to your account. Whichever device you use, you'll pick up where you left off.",
  "İstersen kendini tanıt": "Tell us about yourself",
  "(isteğe bağlı)": "(optional)",
  "Kaydediliyor…": "Saving…",
  "Google ile": "With Google",
  "E-posta ile": "With email",
  "{yol} giriş yapıldı": "Signed in {yol}",
  "Hesap menüsü": "Account menu",
  "Profili düzenle": "Edit profile",
  "Hesabım ve ayarlar": "Account & settings",
  "Eşleşenleri bul": "Find the pairs",
  "Doğru": "Correct",
  "Neredeyse": "Almost",
  "Yanlış": "Wrong",
  "yazdığın:": "you typed:",
  "Kancayla bildin. Bir dahakine kancasız dene.": "You got it with the hook. Try without it next time.",
  "Kancayı göster": "Show the hook",
  "Harfleri sıraya diz": "Put the letters in order",
  "Setteki {n} kelimenin hepsini tanıdın.": "You've met all {n} words in the set.",
  "Hazırlanıyor…": "Preparing…",
  "Kanca panosunu paylaş": "Share your hook board",
  "Yeni kelimeler yakında geliyor. O zamana kadar tekrarlarla devam.": "New words are coming soon. Until then, keep going with reviews.",
  "Seti bitirdin": "You finished the set",
  "Öğren": "Learn",
  "Egzersiz": "Practice",
  "İlerleme": "Progress",
  "Ayarlar": "Settings",
  "Hafızada": "Hafızada",
  "İngilizce": "İngilizce",
  "Hesabım": "My account",
  "Giriş yap ›": "Sign in ›",
  "İngilizcesini yaz…": "Type the English…",
  "Üye ol, ilerlemen kaybolmasın": "Sign up so your progress isn't lost",
  "{ogrenilen} kelimen yalnızca bu cihazda": "Your {ogrenilen} words are only on this device",
  "Telefonda başla, bilgisayarda sürdür.": "Start on your phone, continue on your computer.",
  "Üye ol, cihaza bağlı kalmasın.": "Sign up so they're not tied to this device.",
  "{word} nasil okunur": "How to pronounce {word}",
  "şimdi": "now",
  "{dk} dakika sonra": "in {dk} min",
  "{saat} saat sonra": "in {saat} h",
  "yarın": "tomorrow",
  "{gun} gün sonra": "in {gun} days",
  "{n} hafta sonra": "in {n} weeks",
  "{n} ay sonra": "in {n} months",
  "Bu kadar emeğin tek bir cihazda durmasın. Üye ol, nereden açarsan aç yanında olsun.": "Don't leave all that work on one device. Sign up and take it with you wherever you go.",
  "{p0} gündür aralıksız": "{p0} days in a row",
  "Alışkanlık oluşuyor. Üye olursan bu seri tarayıcını temizlesen de bozulmaz.": "A habit is forming. Sign up and your streak survives even if you clear your browser.",
  "10 kelime oldu": "10 words!",
  "Onu da kancasıyla öğrendin. Üye ol ki bu liste bu cihaza bağlı kalmasın.": "All learned with hooks. Sign up so this list isn't tied to this device.",
  "İlk kelimelerin hazır": "Your first words are in",
  "İlerlemen şu an yalnızca bu cihazda. Hesap açarsan kaybolmaz.": "Right now your progress is only on this device. Create an account and it won't get lost.",
  "Eşleştirme": "Matching",
  "kelime ↔ karşılık": "word ↔ meaning",
  "Çoktan seçmeli": "Multiple choice",
  "İngilizceyi gör, seç": "see the English, pick",
  "Ters seçmeli": "Reverse choice",
  "Türkçeyi gör, seç": "see the Turkish, pick",
  "Harf dizme": "Letter tiles",
  "harfleri sıraya diz": "put the letters in order",
  "Yazma": "Writing",
  "baştan yaz": "type it from scratch",
  "Dinleme": "Listening",
  "yazı yok, sadece ses": "no text, just sound",
  "Tanıdın": "You recognised them",
  "Şimdi kanca ekrandan kalkıyor": "Now the hook leaves the screen",
  "Hatırladın": "You remembered",
  "Şimdi kelimeyi baştan sen yazacaksın": "Now you'll type the word yourself",
  "Ürettin": "You produced it",
  "Merdivenin tepesi": "Top of the ladder",
  "Bugünün kelimeleri hazır.": "Today's words are ready.",
  "Gün": "Day",
  "Hafta": "Week",
  "Ay": "Month",
  "Toplam": "All time",
  "Hafızada İngilizce": "Hafızada İngilizce",
  "Set tamamlandı": "Set complete",
  "Bugünün hedefi": "Today's goal",
  "Günlük hedef tamam ✓": "Daily goal done ✓",
  "Hızlı tekrar": "Quick review",
  "Bugünün {todaysCount} kelimesini istediğin kadar çalış.": "Practise today's {todaysCount} words as much as you like.",
  "Bekleyen tekrarlarını çalışabilirsin.": "You can work through your pending reviews.",
  "Yine de tekrar et": "Review anyway",
  "Bugünlük tamam": "All done for today",
  "Sıradaki tekrar {p0}.": "Next review {p0}.",
  "Yarın görüşürüz.": "See you tomorrow.",
  "Sırada bekleyen {n} kartı öne alır.": "Brings forward {n} upcoming cards.",
  "Hazır": "Ready",
  "Yeni gün": "New day",
  "Bugünün dersi": "Today's lesson",
  "İlk dersin hazır": "Your first lesson is ready",
  "Yeni güne başla": "Start the new day",
  "{n} yeni kelime seni bekliyor.": "{n} new words are waiting for you.",
  "Önce kelimeler, sonra öğrenme testi.": "Words first, then a quick check.",
  "Bugün gelen kelimeler seni bekliyor.": "Today's new words are waiting for you.",
  "Başla": "Start",
  "Önce {n} tekrarı yap": "Do the {n} reviews first",
  "Son tanıştıkların": "Recently met",
  "{n} kelimeyle tanıştın": "You met {n} words",
  "Şimdi kancalar tuttu mu bakalım": "Now let's see if the hooks stuck",
  "Tekrarlar bitti": "Reviews done",
  "Şimdi bugünün yeni kelimeleri": "Now for today's new words",
  "{dogru} / {toplam} doğru": "{dogru} / {toplam} correct",
  "Sırada bekleyen tekrarların": "Up next: your reviews",
  "Yeni kelimeler": "New words",
  "Öğrenme testi": "Learning check",
  "Tekrar": "Review",
  "Bölüm {no}/{toplam} · {ad}": "Part {no}/{toplam} · {ad}",
  "Ders yarıda kalacak": "Your lesson isn't finished",
  "Çıkarsan bu dersin {n} yeni kelimesi kaydedilmez ve ders bir dahakine baştan başlar.": "If you leave, this lesson's {n} new words won't be saved and the lesson starts over next time.",
  "Derse dön": "Back to the lesson",
  "kenara ayrıldı": "set aside",
  "Önceki ders": "Previous lesson",
  "bir önceki dersin kelimeleri": "words from the lesson before",
  "Bekleyen tekrarlar": "Due reviews",
  "vadesi gelmiş {PARTI}": "{PARTI} that are due",
  "Zorlandıklarım": "My tricky words",
  "en çok düştüğüm {PARTI}": "the {PARTI} I miss most",
  "Eski kelimeler": "Older words",
  "{ESKI_GUN}+ günlük, rastgele {PARTI}": "{ESKI_GUN}+ days old, {PARTI} at random",
  "Seç": "Pick",
  "kendin işaretle, sınır yok": "choose them yourself, no limit",
  "{n} seçili": "{n} selected",
  "Kelime seç": "Pick words",
  "Görünenleri seç": "Select visible",
  "Temizle": "Clear",
  "{n} kelime seçildi · Tamam": "{n} words selected · Done",
  "Ders tekrarı · kartlar": "Lesson review · cards",
  "Kartları gözden geçir": "Review the cards",
  "Ders tekrarı · alıştırma": "Lesson review · exercises",
  "Egzersiz bitti": "Practice complete",
  "{dogru} doğru · {yanlis} yanlış": "{dogru} correct · {yanlis} wrong",
  "Henüz kelime yok": "No words yet",
  "Önce birkaç kelime öğren, sonra burada istediğin kadar çalış.": "Learn a few words first, then practise here as much as you like.",
  "Dersi tekrar et": "Review the lesson",
  "bugünün {n} kelimesi": "today's {n} words",
  "bugün henüz ders yapmadın": "no lesson yet today",
  "Hangi kelimeler": "Which words",
  "Bugün": "Today",
  "Son ders": "Last lesson",
  "bugün öğrendiklerim": "what I learned today",
  "{size} kelime seçili · değiştir": "{size} words selected · change",
  "Hangi egzersiz": "Which exercise",
  "Karışık": "Mixed",
  "her kelime kendi basamağında": "each word at its own step",
  "görsel + kanca + cümle": "image + hook + sentence",
  "Başla ({partiSayisi} kelime)": "Start ({partiSayisi} words)",
  "Önce kelime seç": "Pick some words first",
  "Bu seçimde kelime yok": "No words in this selection",
  "Bu dosya okunamadı. Başka bir görsel dene.": "Couldn't read this file. Try another image.",
  "Adsız": "Unnamed",
  "Karıştır": "Shuffle",
  "Adını yaz": "Type your name",
  "Boş bırakırsan sana eğlenceli bir ad seçeriz.": "Leave it empty and we'll pick a fun name for you.",
  "Resmin": "Your picture",
  "Hayvanlar": "Animals",
  "Fotoğraf": "Photo",
  "Başka fotoğraf seç": "Choose another photo",
  "Fotoğraf yükle": "Upload a photo",
  "Fotoğrafın hesabında saklanır, diğer cihazlarında da görünür.": "Your photo is saved to your account and shows on your other devices too.",
  "Fotoğraf yalnızca bu cihazda kalır.": "The photo stays on this device only.",
  "Çerçeven": "Your frame",
  "Çalıştıkça yeni çerçeveler açılır.": "Keep studying to unlock new frames.",
  "Kelimeler": "Words",
  "Öğrendiğin kelimeler ve kancaları": "The words you've learned and their hooks",
  "Başarı": "Accuracy",
  "{toplam} alıştırmanın {dogru} tanesi doğru": "{dogru} of {toplam} exercises correct",
  "{kelime} kelime · {cevap} cevap · {yanlis} yanlış": "{kelime} words · {cevap} answers · {yanlis} wrong",
  "Bu dönemde henüz cevap yok.": "No answers in this period yet.",
  "Bugün çalıştın.": "You studied today.",
  "Bugün henüz çalışmadın.": "You haven't studied today yet.",
  "Toplam {calisilan} gün çalıştın.": "You've studied on {calisilan} days in total.",
  "Son {toplam} günde {calisilan} gün çalıştın.": "You studied on {calisilan} of the last {toplam} days.",
  "kelime öğrendin": "words learned",
  "kalıcılık": "retention",
  "günlük seri": "day streak",
  "toplam çalışma": "total reviews",
  "Kalıcılık": "Retention",
  ": kelimeleri ne kadar sağlam bildiğin. Tekrar ettikçe yükselir.": ": how solidly you know your words. It rises as you review.",
  "Neler yapabildin": "What you've done",
  "Tanıştım": "Met",
  "Türkçesinden seçtim": "Picked from the Turkish",
  "Baştan yazdım": "Typed from scratch",
  "Kancaya bakmadan doğru yaptıkların sayılır.": "Only answers you got right without the hook count.",
  "Seri koruma": "Streak freeze",
  "Bir gün kaçırırsan seriyi korur. 7 günde bir kazanılır.": "Protects your streak if you miss a day. You earn one every 7 days.",
  "Ders bitti": "Lesson complete",
  "{n} kelime çalıştın.": "You studied {n} words.",
  "{n} kelime bir basamak ilerledi": "{n} words moved up a step",
  "{n} kelime": "{n} words",
  "İlk günün": "Your first day",
  "{streak} gündür aralıksız": "{streak} days in a row",
  "Tamamla": "Complete",
  "Ana ekran": "Home",
  "SİL": "DELETE",
  "Hesap silinemedi.": "Couldn't delete the account.",
  "Resmini ve çerçeveni seç": "Choose your picture and frame",
  "Adını ve resmini değiştir": "Change your name and picture",
  "Hesap": "Account",
  "İlerlemen hesabında saklanıyor.": "Your progress is saved to your account.",
  "Ad": "Name",
  "Seviye": "Level",
  "Hedef": "Goal",
  "Bilgilerimi düzenle": "Edit my details",
  "Şifre değiştir": "Change password",
  "İlerlemen şu an": "Right now your progress is",
  "yalnızca bu cihazda": "only on this device",
  ". Giriş yaparsan kaybolmaz.": ". Sign in and it won't get lost.",
  "Günlük hedef": "Daily goal",
  "Yeni kelimeler her gün gece yarısı gelir.": "New words arrive every day at midnight.",
  "kelime": "words",
  "Telaffuz sesi": "Pronunciation audio",
  "Kelimeler kendiliğinden okunsun.": "Read words aloud automatically.",
  "ile dinleyebilirsin.": "to listen.",
  "Günlük hatırlatma": "Daily reminder",
  "Seçtiğin saatte kısa bir bildirim. Kaçırırsan bir şey olmaz.": "A short notification at the time you choose. Missing it is no big deal.",
  "Saat": "Time",
  "Kullanım istatistikleri": "Usage statistics",
  "Hangi ekranların kullanıldığını anonim olarak ölçeriz. Adın, fotoğrafın ve cevapların": "We anonymously measure which screens are used. Your name, photo and answers are",
  "gönderilmez": "never sent",
  "Verilerim": "My data",
  "İlerleme, profilin ve fotoğrafın yalnızca bu cihazda tutuluyor. Taşımak veya korumak için yedekle.": "Your progress, profile and photo are stored on this device only. Back them up to move or protect them.",
  "Açılan menüden Drive'a, e-postaya ya da istediğin yere gönderebilirsin.": "From the menu that opens you can send it to Drive, email or anywhere you like.",
  "Telefona kaydedilemedi.": "Couldn't save to the phone.",
  "Paylaş": "Share",
  "Yedekle": "Back up",
  "Yedek al": "Back up",
  "Geri yükle": "Restore",
  "Sıfırla": "Reset",
  "Yedek dosyası okunamadı.": "Couldn't read the backup file.",
  "Hakkında": "About",
  "Toplam kelime": "Total words",
  "Öğrendiğin": "Learned",
  "Sürüm": "Version",
  "Yasal ve iletişim": "Legal & contact",
  "Gizlilik Politikası": "Privacy Policy (Turkish)",
  "Kullanım Koşulları": "Terms of Use (Turkish)",
  "KVKK Aydınlatma Metni": "KVKK Notice (Turkish)",
  "İletişim": "Contact",
  "Hesabımı kalıcı olarak sil": "Permanently delete my account",
  "Hesabını kalıcı olarak sil": "Permanently delete your account",
  "Bu işlemin geri dönüşü yok. Silinen hiçbir şey kurtarılamaz.": "This can't be undone. Nothing deleted can be recovered.",
  "• Öğrendiğin bütün kelimeler ve ilerlemen": "• All the words you've learned and your progress",
  "• Serin ve bütün çalışma geçmişin": "• Your streak and your entire study history",
  "• Hesabın, e-posta adresin ve bilgilerin": "• Your account, email address and details",
  "• Bu cihazdaki kayıtlar": "• The data on this device",
  "Vazgeçersen Çıkış yap da seçebilirsin; o zaman hesabın durur, yalnızca bu cihaz temizlenir.": "If you change your mind, you can choose Sign out instead — your account stays and only this device is cleared.",
  "Onaylamak için {soz} yaz": "Type {soz} to confirm",
  "Vazgeç, hesabım kalsın": "Cancel, keep my account",
  "Siliniyor…": "Deleting…",
  "Hesabı kalıcı olarak sil": "Delete account permanently",
  "Her şey silinecek": "Everything will be deleted",
  "Öğrendiğin {n} kelime, serin ve tüm geçmişin silinir. Bu geri alınamaz. Yedek almak istersen önce onu yap.": "Your {n} learned words, your streak and your whole history will be deleted. This can't be undone. If you want a backup, make one first.",
  "Evet, sıfırla": "Yes, reset",
  "Hafızada İngilizce yedeği": "Hafızada İngilizce backup",
  "Ezberlemeyeceksin.": "No memorising.",
  "Her İngilizce kelimeyi benzer sesli bir Türkçe kelimeye bağlayacaksın.": "You'll link every English word to a similar-sounding Turkish word.",
  "Kart kayboldu. Sende ne kaldı?": "The card is gone. What stuck?",
  "ne demekti?": "what did it mean?",
  "Hiç ezberlemedin.": "And you didn't memorise a thing.",
  "Olsun.": "That's okay.",
  "Yöntem bu kadar.": "That's the whole method.",
  "Kanca birkaç tekrarda oturur. Acelesi yok.": "Hooks settle in after a few reviews. No rush.",
  "Günde kaç kelime?": "How many words a day?",
  "Her gün bu kadar yeni kelime gelir.": "This many new words arrive each day.",
  "önerilen": "recommended",
  "Sonra Ayarlar'dan değiştirebilirsin.": "You can change this later in Settings.",
  "Hazırım": "I'm ready",
  "Öğrendiklerim": "Learned",
  "Tüm set": "Full set",
  "Bildiklerim": "Already known",
  "“Bunu biliyorum” dediğin kelimeler. İstersen derslere geri ekleyebilirsin.": "Words you marked “I know this”. You can add them back to your lessons.",
  "Henüz öğrenilmedi": "Not learned yet",
  "Eşleşen kelime yok.": "No matching words.",
  "Görsel üretilemedi": "Couldn't create the image",
  "Üye": "Member",
  "Hiç bilmiyorum": "Beginner",
  "Biraz anlıyorum": "I know a little",
  "Orta seviye": "Intermediate",
  "İş": "Work",
  "Seyahat": "Travel",
  "Sınav": "Exams",
  "Kendim için": "For myself",
  "Çok fazla deneme oldu. Birkaç dakika sonra tekrar dene.": "Too many attempts. Try again in a few minutes.",
  "E-posta ya da şifre hatalı. Daha önce e-posta bağlantısıyla girdiysen şifren yok. \"Şifremi unuttum\" ile bir tane oluştur.": "Wrong email or password. If you used to sign in with an email link, you don't have a password yet. Create one with \"Forgot password\".",
  "Bu adres zaten kayıtlı. Giriş yapmayı dene.": "This email is already registered. Try signing in.",
  "Adresini henüz doğrulamadın. Kayıt e-postandaki bağlantıya dokun.": "You haven't verified your email yet. Tap the link in your sign-up email.",
  "Şifre en az {SIFRE_EN_AZ} karakter olmalı.": "Your password needs at least {SIFRE_EN_AZ} characters.",
  "Bu e-posta adresi geçerli görünmüyor.": "This email address doesn't look valid.",
  "Bir şeyler ters gitti. Biraz sonra tekrar dene.": "Something went wrong. Please try again shortly.",
  "Şu an bağlanamıyoruz. Biraz sonra dene.": "We can't connect right now. Try again shortly.",
  "Bu adres zaten kayıtlı. \"Giriş yap\" ile devam et; şifreni bilmiyorsan \"Şifremi unuttum\" de.": "This email is already registered. Continue with \"Sign in\"; if you don't know your password, choose \"Forgot password\".",
  "Adını yazman gerekiyor.": "Please enter your name.",
  "Önce giriş yapman gerekiyor.": "You need to sign in first.",
  "Hesap silinemedi. Biraz sonra tekrar dene.": "Couldn't delete the account. Please try again shortly.",
  "Meraklı": "Curious",
  "Çevik": "Nimble",
  "Neşeli": "Cheerful",
  "Sakin": "Calm",
  "Cesur": "Brave",
  "Zeki": "Clever",
  "Şen": "Jolly",
  "Hızlı": "Quick",
  "Uyanık": "Sharp",
  "Kıvrak": "Agile",
  "Titiz": "Tidy",
  "Atak": "Bold",
  "Tilki": "Fox",
  "Baykuş": "Owl",
  "Fil": "Elephant",
  "Ayı": "Bear",
  "Kedi": "Cat",
  "Ördek": "Duck",
  "Balık": "Fish",
  "Arı": "Bee",
  "Yılan": "Snake",
  "Atla": "Skip",
  "Bak": "Check",
  "Bunu biliyorum": "I know this",
  "Geri al": "Undo",
  "Kapat": "Close",
  "Sonra": "Later",
  "Telefona kaydet": "Save to phone",
  "Geri ekle": "Add back",
  "Tekrar dinle": "Listen again",
  "ornek@eposta.com": "you@example.com",
  "Geri": "Back",
  "Kelime, anlam veya kanca ara…": "Search words, meanings or hooks…",
  "Bitti": "Done",
  "{n} yeni kelime": "{n} new words",
  "{n} tekrar": "{n} reviews",
  "Yeni kelimeler yarın gelir.": "New words arrive tomorrow.",
  "{a} / {b} kelime": "{a} / {b} words",
  "İlk ders": "First lesson",
  "Hesap aç, kelimelerin her cihazda seninle olsun.": "Create an account and keep your words on every device.",
  "{n} yeni kelime öğrendin": "You learned {n} new words",
  "{n} kelime tekrar ettin": "You reviewed {n} words",
  "{n} kelime daha sağlam": "{n} words got stronger",
  "Hızlı pratik": "Quick practice",
  "{n} kelime, uygulama seçer": "{n} words, picked for you",
  "Kartlara göz at": "Browse cards",
  "Kendin seç": "Choose yourself",
  "Önce kelime grubu seç": "Pick a word group first",
  "uygulama seçsin": "let the app pick",
  "Kartlar": "Cards",
  "görsel, kanca, cümle": "image, hook, sentence",
  "tekrar zamanı gelenler": "due for review",
  "en çok yanıldıkların": "your most missed",
  "{ESKI_GUN} günden eski": "older than {ESKI_GUN} days",
  "listeden işaretle": "pick from the list",
  "Tamam ({n} kelime)": "Done ({n} words)",
  "{size} kelime seçili": "{size} words selected",
  "Ders tekrarı": "Lesson review",
};
